### ISSUE TITLE
app crashed - Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#130]
I cannot test or deploy main because it crashes.
```
Morpheus-2:loklak_webclient admin$ npm install
Morpheus-2:loklak_webclient admin$ gulp dev
[18:16:30] Warning: gulp version mismatch:
[18:16:30] Global gulp is 3.9.0
[18:16:30] Local gulp is 3.8.11
[18:16:35] Using gulpfile ~/git/loklak_webclient/gulpfile.js
[18:16:35] Starting 'clean'...
[18:16:35] Finished 'clean' after 18 ms
[18:16:35] Starting 'dev'...
[18:16:35] Starting 'styles'...
[18:16:35] Starting 'minify-css'...
[18:16:35] Starting 'photoswipe-icons'...
[18:16:35] Starting 'images'...
[18:16:35] Starting 'fonts'...
[18:16:35] Starting 'views'...
[18:16:35] Starting 'browserify'...
[18:16:35] Rebundle...
[18:16:35] Starting 'admin-js'...
[18:16:35] Finished 'photoswipe-icons' after 180 ms
[18:16:36] Finished 'admin-js' after 1.32 s
[18:16:36] Finished 'fonts' after 1.4 s
[18:16:36] Finished 'styles' after 1.43 s
[18:16:36] Finished 'views' after 1.49 s
[18:16:37] Rebundle...
[18:16:40] Finished 'images' after 5.22 s
[18:16:41] Finished 'browserify' after 6.55 s
[18:16:41] Finished 'minify-css' after 6.62 s
[18:16:41] Starting 'server'...
[18:16:41] [nodemon] v1.3.7
[18:16:41] [nodemon] to restart at any time, enter `rs`
[18:16:41] [nodemon] watching: *.*
[18:16:41] [nodemon] starting `node server/index.js`
[18:16:41] Finished 'server' after 36 ms
[18:16:41] Starting 'browserSync'...
[18:16:41] Finished 'browserSync' after 58 ms
[18:16:41] Starting 'watch'...
[18:16:42] Finished 'watch' after 85 ms
[18:16:42] Finished 'dev' after 6.81 s
[BS] Proxying: http://localhost:3001
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:3000
[BS] External URL: http://192.168.43.66:3000
module.js:338
    throw err;
          ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/admin/git/loklak_webclient/server/index.js:18:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
[18:16:42] [nodemon] app crashed - waiting for file changes before starting...

```

**Comment by aneeshd16** [comment]
Did you also do an `npm install` inside the server directory?

**Comment by Orbiter** [comment]
oh no ...
ok its working!
