### ISSUE TITLE
version `GLIBC_2.14' not found required by imagemin-jpegtran

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#151]
I did a complete fresh install, removed all npm stuff in my home folder, killed all processes, run all npm install commands and when I started ```gulp prod```I get the following error:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Error: write EPIPE/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran)
```
..while ```gulp dev```works.
I checked that no other process is running (```killall node```)

**Comment by sudheesh001** [comment]
@fuksi Any idea ?

**Comment by Orbiter** [comment]
I'm stuck here. Do we need the module /home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran ?

**Comment by Orbiter** [comment]
The ```npm install``` log has errors in it related to this issue:
```
  ⚠ The `/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran` binary doesn't seem to work correctly
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --disable-shared --prefix="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install
Command failed: /bin/sh -c ./configure --disable-shared --prefix="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor"
configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

> gifsicle@3.0.0 postinstall /home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ The `/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle` binary doesn't seem to work correctly
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" --bindir="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" && make install
Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by Orbiter** [comment]
I installed nasm and actually jpegtran was compiled from source
```
  ⚠ The `/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran` binary doesn't seem to work correctly
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✔ jpegtran built successfully

> optipng-bin@3.0.2 postinstall /home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@3.0.0 postinstall /home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

> gifsicle@3.0.0 postinstall /home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ The `/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle` binary doesn't seem to work correctly
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" --bindir="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" && make install
Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found
```

**Comment by aneeshd16** [comment]
@Orbiter , does this help? http://askubuntu.com/a/421795

**Comment by Orbiter** [comment]
now installed ```dh-autoreconf``` since there is a dependency on ```autoreconf```:
```
  ⚠ The `/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle` binary doesn't seem to work correctly
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" --bindir="/home/loklak/loklak_webclient/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor" && make install
Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

**Comment by Orbiter** [comment]
wow. that did the job!
```
gulp prod
[11:54:51] Using gulpfile ~/loklak_webclient/gulpfile.js
[11:54:51] Starting 'clean'...
[11:54:51] Finished 'clean' after 20 ms
[11:54:51] Starting 'prod'...
[11:54:51] Starting 'styles'...
[11:54:51] Starting 'minify-css'...
[11:54:51] Starting 'photoswipe-icons'...
[11:54:51] Starting 'images'...
[11:54:51] Starting 'fonts'...
[11:54:51] Starting 'views'...
[11:54:51] Starting 'browserify'...
[11:54:51] Rebundle...
[11:54:51] Starting 'admin-js'...
[11:54:52] Finished 'styles' after 1.29 s
[11:54:52] Finished 'photoswipe-icons' after 1.28 s
[11:54:53] Finished 'admin-js' after 2.19 s
[11:54:54] Finished 'fonts' after 2.79 s
[11:54:55] Finished 'views' after 4.52 s
Note: The code generator has deoptimised the styling of "/home/loklak/loklak_webclient/app/js/components/leaflet.js" as it exceeds the max of "100KB".
[11:55:04] gulp-imagemin: Minified 22 images (saved 75.54 kB - 13.5%)
[11:55:06] Finished 'images' after 16 s
[11:55:25] Finished 'browserify' after 35 s
[11:55:26] Finished 'minify-css' after 35 s
[11:55:26] Starting 'gzip'...
[11:55:26] Finished 'gzip' after 415 ms
[11:55:26] Finished 'prod' after 35 s
```
Thats the solution: https://github.com/loklak/loklak_webclient/commit/8cadcb7d19cc0ec6de9e3ebd05f5ca73261be7c3
