### ISSUE TITLE
A problem with the dumps

### ISSUE THREAD

**Issue by d33tah** [loklak/loklak_webclient#542]
Not sure if it's the right repository to report that, but I took a look at your dump repository and found it's not valid JSON:

```
>>> s
'{"created_at":"2015-06-05T13:21:01.000Z","screen_name":"bildungkirche","text":"Die Kirchen Bern-Jura-Solothurn gehen in die Zukunft. Ihr Start-Video f\xc3\xbcr den Prozess "Vision Kirche 21" https://vimeo.com/129694062","link":"https://twitter.com/bildungkirche/status/606812974662197248","id_str":"606812974662197248","source_type":"TWITTER","provider_type":"REMOTE","provider_hash":"7ffffffe","retweet_count":0,"favourites_count":0,"images":[],"images_count":0,"place_name":"","place_id":"","user":{"name":"bildungkirche","screen_name":"bildungkirche","profile_image_url_https":"https://pbs.twimg.com/profile_images/478436365474885633/_5zoJJmK_bigger.jpeg","appearance_first":"2015-06-05T13:31:28.590Z","appearance_latest":"2015-06-05T13:31:28.590Z"}}'
>>> pprint.pprint(json.loads(s))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1 column 168 (char 167)
>>> s[160:190]
'ozess "Vision Kirche 21" https'
```

You can see unescaped `"`. Found somewhere in http://loklak.org/dump/messages_201506_68404958.txt.gz.

**Comment by DengYiping** [comment]
@d33tah  Please move to loklak_server repo

**Comment by d33tah** [comment]
https://github.com/loklak/loklak_server/issues/175

**Comment by d33tah** [comment]
@DengYiping
