### ISSUE TITLE
Implement twitter auth on the node server

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_webclient#80]
Used passportjs (passportjs.org) to create a basic twitter authentication flow on a node/express server. The routes are:
/auth/twitter to begin login
/auth/twitter/callback callback URL
/account page once the user has logged in
The session is automatically managed by express.

Further objectives
* Store and read the keys from the config file
* Scaffolding code for storing user credentials

**Comment by sudheesh001** [comment]
Hi @aneeshd16 , 

I've pulled from upstream and tried to see if this is working and maintaining a session, I am facing the following problems.

Firstly,
```
Error: {"errors":[{"code":32,"message":"Could not authenticate you."}]}
    at Strategy.parseErrorResponse (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/loklak_webclient/server/node_modules/passport-twitter/lib/strategy.js:182:10)
    at Strategy.OAuthStrategy._createOAuthError (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/loklak_webclient/server/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:349:16)
    at /Users/sudheeshsinganamalla/Documents/loklak_GSoC/loklak_webclient/server/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:218:41
    at /Users/sudheeshsinganamalla/Documents/loklak_GSoC/loklak_webclient/server/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/loklak_webclient/server/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/loklak_webclient/server/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```
All the Twitter consumer keys and other details for the app are correct, at times It lands me to an `ERR CONNECTION REFUSED`

``` GET http://loklak.net:3000/auth/twitter/callback?oauth_token=<TOKEN>&oauth_verifier=<Other secure stuff> net::ERR_CONNECTION_REFUSED ```

Is there something going wrong, Could you update the documentation on how this change has to be incorporated, I've done an npm install on both the server/ folder and the loklak_webclient folder.

**Comment by aneeshd16** [comment]
@sudheesh001 , please check if your keys are in `custom_configFile.json` and not `configFile.json`. Also see if you can `console.log()` them. Apart from this I cant think of what might be causing this since the auth code is unchanged. Its most likely a problem in reading the keys.

**Comment by sudheesh001** [comment]
I have the keys present in the `custom_configFile.json` itself, Still reproducing the same error, the CONNECTION REFUSED after doing /auth/twitter

**Comment by aneeshd16** [comment]
My config file looks like this
````
{
	"apiUrl": "http://localhost:9100/api/",
	"domain": "http://localhost:3001",
	"twitterConsumerKey": "<KEY>",
	"twitterConsumerSecret": "<SECRET>",
	"twitterCallbackUrl": "http://localhost:3000/auth/twitter/callback"
}
````
In index.js, after line 7, can you do a `console.log(config);` and see what happens?

**Comment by sudheesh001** [comment]
I am able to get all the details, my hosts file has 127.0.0.1 aliased to loklak.net, so my twitterCallbackUrl is `http://loklak.net:3000/auth/twitter/callback`

**Comment by sudheesh001** [comment]
@aneeshd16 I am still facing this issue, Can you help me resolve this as this is required for me to progress with the rest of my work, Here's the complete stack trace
```
Error: Failed to find request token in session
    at Strategy.OAuthStrategy.authenticate (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:142:54)
    at Strategy.authenticate (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/passport-twitter/lib/strategy.js:85:40)
    at attempt (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/express/lib/router/layer.js:82:5)
    at /Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/sudheeshsinganamalla/Documents/loklak_GSoC/webclient/server/node_modules/express/lib/router/index.js:321:12)
```
