### ISSUE TITLE
Error: Cannot find module 'cookie-parser'

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_webclient#86]
app (everything/anything) crashes upon start :(

I did a pull on main, did a "npm install", then "gulp dev" and got
```
[BS] Proxying: http://localhost:3001
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:3000
[BS] External URL: http://192.168.1.56:3000
module.js:338
    throw err;
          ^
Error: Cannot find module 'cookie-parser'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/admin/git/loklak_webclient/server/index.js:5:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
[22:41:01] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by sudheesh001** [comment]
@Orbiter You need to do the `npm install` in two different location, firstly in the `loklak_webclient` folder and again in the `server/` folder.

**Comment by Orbiter** [comment]
ah ok, please add such information to the README, just did that in https://github.com/loklak/loklak_webclient/commit/fab0e2eb125fe677e1db6c9f98bfa8faab1e0d20

**Comment by PremkumarAgrawal** [comment]
Facing issues while initializing MEAN project with,

Error: Cannot find module 'cookie-parser'
